# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogseries', '0016_blog_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFbId', models.TextField(default='')),
                ('userGoogleId', models.TextField(default='')),
                ('userEmailId', models.TextField(default='')),
                ('response', models.IntegerField(default=0)),
                ('otherdata', models.TextField(blank=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogseries.Blog')),
            ],
        ),
    ]
