# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0002_auto_20171014_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Series_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_series_genre',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=tagulous.models.fields.SingleTagField(_set_tag_meta=True, blank=True, force_lowercase=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogseries.Tagulous_Series_genre'),
        ),
    ]
