# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0003_auto_20171014_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='Tagulous_Blogs_tags',
            new_name='Tagulous_Blog_tags',
        ),
    ]
