# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0007_auto_20171027_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Profile'),
        ),
        migrations.AlterField(
            model_name='series',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Profile'),
        ),
    ]
