# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0008_auto_20171027_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='folder',
            field=models.CharField(choices=[('BL', 'Blog'), ('GL', 'Gallery')], default='BL', max_length=2),
        ),
        migrations.AddField(
            model_name='blog',
            name='hidden_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
