# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0009_auto_20171104_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='pub_date',
            new_name='create_date',
        ),
    ]
