# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0010_auto_20171104_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='publishable',
            field=models.BooleanField(default=False),
        ),
    ]
