# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0011_auto_20171104_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Series_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.RenameField(
            model_name='series',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='series',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_series_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=10, to='blogseries.Tagulous_Series_tags'),
        ),
    ]
