# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0012_auto_20171104_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, upload_to='series_images'),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
