# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-10 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0014_auto_20171105_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='series_images'),
        ),
    ]
