# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-10 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0015_auto_20180710_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='responses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
