# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-10 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0016_blog_responses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='responses',
            new_name='neg_responses',
        ),
        migrations.AddField(
            model_name='blog',
            name='pos_responses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
