# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0017_auto_20180710_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Profile'),
        ),
    ]
