# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-19 20:18
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0018_auto_20180716_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=8, to='blogseries.Tagulous_Blog_tags'),
        ),
    ]
