# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-19 20:24
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0019_auto_20180719_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=5, to='blogseries.Tagulous_Series_genre'),
        ),
    ]
