# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 10:37
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0020_auto_20180719_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=6, to='blogseries.Tagulous_Series_genre'),
        ),
    ]
