# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0021_auto_20180724_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
