# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-06 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogseries', '0023_auto_20180725_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
