# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('is_moderator', 'Can Moderate Others'),)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='pen_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
