# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20180716_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pen_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
