# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-19 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20180719_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='dsa', max_length=100),
            preserve_default=False,
        ),
    ]
