# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-19 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20180719_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Profile_interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_profile_interests',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, force_lowercase=True, help_text='Enter a comma-separated tag string', max_count=10, to='userprofile.Tagulous_Profile_interests'),
        ),
    ]
