# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-25 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20180719_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='bio_summary',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_full',
            field=models.TextField(blank=True),
        ),
    ]
